Mozilla-Campus-Club-Cummins/Hacktoberfest_Moz_Cummins

Solutions/Problem_Statement_31_Solution.py
Submitted the solution for assigned issue.
=> Added solution for problem statement 31

Solutions/Problem_Statement_39_Solution.py
=> Solution for problem statement 39

Solutions/Problem_Statement_7_Solution.java
Created Pull Request for issue number #37
=> Add Aarya Khodke to Contributors list

Solutions/ProblemStatement_5.java
=> solution for problem statement 5

Solutions/Problem_Statement_40_Solution.py
I have written the code for the problem no. 40.
=> Solution to problem no. 40

Solutions/Problem_Statement_50.java
Problem Statement 50 solved by java
=> Problem_Statement_50 Solved by Java

Solutions/Problem_Statement_54_Solution.java
Problem_Statement_54 #36 Solution Submitted
Added by Sravya Srusti
=> Problem_Statement_54_Solution

Solutions/Problem_statemet_32.java
=> created the solution for problem statement 46 #32

Solutions/Problem_Statement_47_Solution.c
=> Created solution for Problem_Statement_47_Solution

Solutions/Problem_Statement_12_Solution.cpp
=> Created solution for Problem Statement 12

Solutions/Problem_Statement_28_Solution.java
=> Created solution for issue 12

Solutions/Problem_Statement_29_Solution.py
Solution for Issue #15 
Problem statement 29 solved in python.
=> Added solution for Problem statement 29

Solutions/Problem_Statement_80_solution.cpp
=> Created Problem_Statement_80_Solution.cpp

Solutions/Problem_Statement_30_Solution.java, Solutions/Problem_Statement_30_Solution.java.java
=> Created solution for issue #16

Solutions/Problem_Statement_23.java
=> Created solution for problem 23

Solutions/Problem_Statement_30_Solution.java
=> Created solution for Problem_Statement_30

Solutions/Problem_Statement_22_Solution.java
=> Solution for problem 22 issue #42

Solutions/Problem_Statement_2_Solution.java
Problem_Statement_2_Solution By Gayatri Chaudhari
=> Problem_Statement_2_Solution

Solutions/Problem_Statement_15.java
For issue #33
Problem statement 25
=> created PR for #25

Solutions/Problem_Statement_57_Solution.java
Created solution for Problem_Statement_57_Solution_issue #17
=> Created solution for Problem_Statement_57_Solution_issue#17

Solutions/Problem_Statement_36_Solution.java
#40 Added solution for Problem statement 36
Created solution for #40
=> Added solution for Problem statement 36

Solutions/Problem_Statement_55_Solution.py
=> Solution for Problem Statement 55

Solutions/Problem_Statement_6 Solution.py
Added Solution for problem 6 #23
=> Problem_Statement_6_Solution.py

Solutions/Problem_Statement_26_Solution.java
created solution for issue #34
=> created solution for issue #34

Solutions/Problem_Statement_53_Solution.py
=> Added solution to problem 53

Solutions/Problem_Statement_3_Solution.java
=> Problem_Statement_3_Solution
